/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Draaa
 */
public class MenuDashboard extends javax.swing.JPanel {

    /**
     * Creates new form menuDashboard
     */
    public MenuDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cardAnggota = new Castom.PanelCustom();
        lb_anggota = new javax.swing.JLabel();
        lb_jumlahAnggota = new javax.swing.JLabel();
        lb_icon3 = new javax.swing.JLabel();
        cardAnggota1 = new Castom.PanelCustom();
        lb_anggota1 = new javax.swing.JLabel();
        lb_jumlahAnggota1 = new javax.swing.JLabel();
        lb_icon1 = new javax.swing.JLabel();
        cardAnggota2 = new Castom.PanelCustom();
        lb_anggota2 = new javax.swing.JLabel();
        lb_jumlahAnggota2 = new javax.swing.JLabel();
        lb_icon2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCastom2 = new Castom.JTableCastom();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        cardAnggota.setBackground(new java.awt.Color(102, 204, 255));
        cardAnggota.setPreferredSize(new java.awt.Dimension(196, 129));
        cardAnggota.setRoundBottomLeft(30);
        cardAnggota.setRoundBottomRight(30);
        cardAnggota.setRoundTopLeft(30);
        cardAnggota.setRoundTopRight(30);

        lb_anggota.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lb_anggota.setForeground(new java.awt.Color(102, 102, 102));
        lb_anggota.setText("Tiket Aktif");

        lb_jumlahAnggota.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lb_jumlahAnggota.setForeground(new java.awt.Color(0, 102, 153));
        lb_jumlahAnggota.setText("999");

        lb_icon3.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lb_icon3.setForeground(new java.awt.Color(0, 102, 153));
        lb_icon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Dashboartiket1.png"))); // NOI18N

        javax.swing.GroupLayout cardAnggotaLayout = new javax.swing.GroupLayout(cardAnggota);
        cardAnggota.setLayout(cardAnggotaLayout);
        cardAnggotaLayout.setHorizontalGroup(
            cardAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardAnggotaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_anggota)
                    .addGroup(cardAnggotaLayout.createSequentialGroup()
                        .addComponent(lb_jumlahAnggota)
                        .addGap(18, 18, 18)
                        .addComponent(lb_icon3)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        cardAnggotaLayout.setVerticalGroup(
            cardAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardAnggotaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardAnggotaLayout.createSequentialGroup()
                        .addComponent(lb_anggota)
                        .addGap(20, 20, 20)
                        .addComponent(lb_jumlahAnggota))
                    .addGroup(cardAnggotaLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lb_icon3)))
                .addGap(22, 22, 22))
        );

        cardAnggota1.setBackground(new java.awt.Color(102, 204, 255));
        cardAnggota1.setPreferredSize(new java.awt.Dimension(196, 129));
        cardAnggota1.setRoundBottomLeft(30);
        cardAnggota1.setRoundBottomRight(30);
        cardAnggota1.setRoundTopLeft(30);
        cardAnggota1.setRoundTopRight(30);

        lb_anggota1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lb_anggota1.setForeground(new java.awt.Color(102, 102, 102));
        lb_anggota1.setText("Pengadaan Baru");

        lb_jumlahAnggota1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lb_jumlahAnggota1.setForeground(new java.awt.Color(0, 102, 153));
        lb_jumlahAnggota1.setText("999");

        lb_icon1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lb_icon1.setForeground(new java.awt.Color(0, 102, 153));
        lb_icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Dashboardpengadaan1.png"))); // NOI18N

        javax.swing.GroupLayout cardAnggota1Layout = new javax.swing.GroupLayout(cardAnggota1);
        cardAnggota1.setLayout(cardAnggota1Layout);
        cardAnggota1Layout.setHorizontalGroup(
            cardAnggota1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardAnggota1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardAnggota1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(cardAnggota1Layout.createSequentialGroup()
                        .addComponent(lb_anggota1)
                        .addGap(94, 94, 94))
                    .addGroup(cardAnggota1Layout.createSequentialGroup()
                        .addComponent(lb_jumlahAnggota1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_icon1)
                        .addGap(28, 28, 28))))
        );
        cardAnggota1Layout.setVerticalGroup(
            cardAnggota1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardAnggota1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_anggota1)
                .addGroup(cardAnggota1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardAnggota1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lb_jumlahAnggota1))
                    .addGroup(cardAnggota1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_icon1)))
                .addGap(27, 27, 27))
        );

        cardAnggota2.setBackground(new java.awt.Color(102, 204, 255));
        cardAnggota2.setPreferredSize(new java.awt.Dimension(196, 129));
        cardAnggota2.setRoundBottomLeft(30);
        cardAnggota2.setRoundBottomRight(30);
        cardAnggota2.setRoundTopLeft(30);
        cardAnggota2.setRoundTopRight(30);

        lb_anggota2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lb_anggota2.setForeground(new java.awt.Color(102, 102, 102));
        lb_anggota2.setText("Peminjaman Aktif");

        lb_jumlahAnggota2.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lb_jumlahAnggota2.setForeground(new java.awt.Color(0, 102, 153));
        lb_jumlahAnggota2.setText("999");

        lb_icon2.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lb_icon2.setForeground(new java.awt.Color(0, 102, 153));
        lb_icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Dashboardpeminjaman1.png"))); // NOI18N

        javax.swing.GroupLayout cardAnggota2Layout = new javax.swing.GroupLayout(cardAnggota2);
        cardAnggota2.setLayout(cardAnggota2Layout);
        cardAnggota2Layout.setHorizontalGroup(
            cardAnggota2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardAnggota2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardAnggota2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_anggota2)
                    .addGroup(cardAnggota2Layout.createSequentialGroup()
                        .addComponent(lb_jumlahAnggota2)
                        .addGap(28, 28, 28)
                        .addComponent(lb_icon2)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        cardAnggota2Layout.setVerticalGroup(
            cardAnggota2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardAnggota2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_anggota2)
                .addGroup(cardAnggota2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardAnggota2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lb_jumlahAnggota2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardAnggota2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_icon2)))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Tiket Terbaru");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Master Data > Dashboard");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dashboard (1).png"))); // NOI18N

        jTableCastom2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableCastom2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(cardAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(88, 88, 88)
                                    .addComponent(cardAnggota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(100, 100, 100)
                                    .addComponent(cardAnggota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(69, 69, 69))
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(18, 18, 18)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cardAnggota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardAnggota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Castom.PanelCustom cardAnggota;
    private Castom.PanelCustom cardAnggota1;
    private Castom.PanelCustom cardAnggota2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private Castom.JTableCastom jTableCastom2;
    private javax.swing.JLabel lb_anggota;
    private javax.swing.JLabel lb_anggota1;
    private javax.swing.JLabel lb_anggota2;
    private javax.swing.JLabel lb_icon1;
    private javax.swing.JLabel lb_icon2;
    private javax.swing.JLabel lb_icon3;
    private javax.swing.JLabel lb_jumlahAnggota;
    private javax.swing.JLabel lb_jumlahAnggota1;
    private javax.swing.JLabel lb_jumlahAnggota2;
    // End of variables declaration//GEN-END:variables
}
